version: '3.3'

services:

  app:
    container_name: fdp-app-${NODE_ENV}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=${PORT}
        - ENV=${NODE_ENV}
    networks:
      - web
    labels:
      - "traefik.frontend.rule=Host:${TRAEFIK_HOST_API}"
      - "traefik.backend=${NODE_ENV}-app-fdp"
      - "traefik.docker.network=web"
      - "traefik.enable=true"

networks:
  web:
    external: true
