name: CI

on: [push]

jobs:
  test:
    name: Test
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.8
      uses: actions/setup-node@v1
      with:
        node-version: 12.8
    - name: Install
      run: yarn install
    - name: Lint
      run: yarn lint
    - name: Test
      run: yarn test --watch=false --browsers=ChromeHeadlessCustom

  build:
    name: Build SSR
    runs-on: [ubuntu-latest]
    needs: [test]
    steps:
    - name: Install
      uses: actions/app-fdp@v1
#      run: yarn install
#    - name: Build
#      run: yarn build:ssr
