name: CI

on: [push]

jobs:
  test:
    name: Tests
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.8
      uses: actions/setup-node@v1
      with:
        node-version: 12.8
    - name: Install
      run: yarn install
    - name: Lint
      run: yarn lint
    - name: Test
      run: yarn test --watch=false --browsers=ChromeHeadlessCustom

  build:
    name: Build SSR app image and push to docker hub
    runs-on: [ubuntu-latest]
    needs: [test]
    steps:
    - name: Chekout
      uses: actions/checkout@v1
    - name: Build and Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: aifedespaix/app_fdp
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

  deploy:
    name: Connect to prod and compose up
    runs-on: [ubuntu-latest]
    needs: [build]
    steps:
      - name: SSH Commands
        uses: appleboy/ssh-action@v0.0.2
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: ls -la

# todo https://github.com/marketplace/actions/telegram-notify
